name: spack
on: [ push, workflow_dispatch ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:

      - name: apt install dependencies
        run: |
          sudo apt install libz-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext cmake gcc curl xz

      - name: download and extract source for git-scm
        run: |
          curl --output git.tar.gz https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.43.0.tar.gz
          tar xf ./git.tar.gz

      - name:
        run: |
          ls -la
          pwd

