name: spack
on: [ push, workflow_dispatch ]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:

      - name: apt install dependencies
        run: |
          sudo apt install -y \
            libz-dev \
            libssl-dev \
            libcurl4-gnutls-dev \
            libexpat1-dev \
            gettext \
            cmake \
            gcc \
            curl \
            build-essential \
            gcc \
            bc \
            bison \
            flex \
            libssl-dev \
            libncurses5-dev \
            libelf-dev

